# Generated by Django 5.0.7 on 2024-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRoperations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(default=1000, max_length=10),
        ),
    ]
